Add specification for fees communication
many-protocol/specification pull request #92
Opened 2023-05-10 21:23 UTC by hansl

2023-05-16 19:32 UTC, MavenRain approved these changes

2023-05-16 19:33 UTC, MavenRain commented
It looks like the rustc version needs to be updated on the repo, but looks good otherwise.

2023-05-16 20:05 UTC, fmorency requested changes
The first round of comments. I'm still not done. I'll finish tomorrow morning.

2023-05-16 20:05 UTC, fmorency commented on attributes/network/cddl/15_fee.cddl
> +    ; in human and/or machine readable format. It is optional.
```suggestion
    ; in human and/or machine readable format.
```

2023-05-16 20:50 UTC, hansl commented on attributes/network/9_account_features/15_account_fee.adoc
> +Identities MUST either be an `"owner"` or have this role to be allowed to use this account to pay for requests.
It becomes muddy when we want to add payment for another's account on anything else. I'll clarify, but it's gonna get complex really fast.

2023-05-16 20:50 UTC, hansl commented on attributes/network/9_account_features/15_account_fee.adoc
> +Identities MUST either be an `"owner"` or have this role to be allowed to use this account to pay for requests.
Basically, anything that's not a request should be owner paid. At least for now.

2023-05-16 20:51 UTC, hansl commented on attributes/network/15_fee.adoc
> +// TODO: Requests to the neighborhood, receiver pays.
I'll remove it. We'll expand on fee table entries for those.

2023-06-06 19:36 UTC, hansl commented
We should support this but at a later time when we have a better idea. Let's close it for now.

2023-06-06 19:36 UTC, closed without merging